version: "3"
services:
  db:
    build:
      context: ./infra/mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: webapi_db

volumes:
  mysql_data:

