FROM mysql:8.0

ENV MYSQL_DATABASE=webapi_db
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin
ENV MYSQL_ROOT_PASSWORD=admin
ENV TZ=Asia/Tokyo

COPY ./my.cnf /etc/mysql/conf/.d/my.cnf

VOLUME /var/lib/mysql

EXPOSE 3306
